### ISSUE TITLE
request: customize arrows and fatter lines

### ISSUE THREAD

**Issue by ralyodio** [dragonman225/curved-arrows#2]
How hard would it be to provide an svg for beginning and ending arrows as an option?

Also line width seems to be fixed.

**Comment by dragonman225** [comment]
Do you mean "arrow heads" (the little triangle at the start or the end of an arrow)?

**Comment by ralyodio** [comment]
yeah

**Comment by dragonman225** [comment]
Umm it's not hard to provide an option, but I don't think it's a good practice to include that feature here, for two reasons:
1. There are too many types of arrow heads: triangle, circle, filled with color or outlined, .... People have many preferences, it's not manageable.
2. Likewise, people may want to draw them with different technologies: SVG, HTML Elements, Canvas, Native GUI technologies, ...

It may make more sense to build another library for specific use case like "arrow heads with SVG for React" for this feature.
