### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by AlexanderMykulych** [dragonman225/curved-arrows#5]
I just wanted to say thank you for this tiny library! 
It saves me a lot of time 😊
Here is an example, how I use it in my library
![Peek 2022-01-01 23-34](https://user-images.githubusercontent.com/7901909/147860645-721fc809-1f5b-4005-a2e7-aa9f4a53312a.gif)

**Comment by dragonman225** [comment]
The project is cool!

A suggestion: you can create "an arrow being drawn" with this library by setting the end box's width and height to zero.

https://user-images.githubusercontent.com/25148955/147905833-d08a9968-222b-4d82-8035-f08d937bd753.mp4

**Comment by AlexanderMykulych** [comment]
> The project is cool!
> 
> A suggestion: you can create "an arrow being drawn" with this library by setting the end box's width and height to zero.
> 
>  kazam_screencast_00000.mp4

Unfortunately, something with a video that you've sent, can see nothing(

**Comment by dragonman225** [comment]
![image](https://user-images.githubusercontent.com/25148955/147907397-d00dc7b6-3a98-4bef-a9b9-3719f1611a31.png)

It's a video showing me dragging an arrow from a block in this [canvas](https://dragonman225.js.org/p/jade/index.html).

**Comment by AlexanderMykulych** [comment]
Ohh now I can watch your video, it was something with my phone.
Yeah, really good idea 🚀
![Peek 2022-01-03 13-00](https://user-images.githubusercontent.com/7901909/147923476-368e3119-8f4e-4491-9dd8-8a516777aeb9.gif)
