### ISSUE TITLE
`controlPointStretch` option not published to npm

### ISSUE THREAD

**Issue by ChrisShank** [dragonman225/curved-arrows#7]
I see in the [current source code](https://github.com/dragonman225/curved-arrows/blob/main/src/getBoxToBoxArrow.ts#L33) and demo that `controlPointStretch` is an option, but it seems like this has not been published to npm or updated in the README documentation. Would love to see that if possible!

**Comment by dragonman225** [comment]
Hi @ChrisShank, you can now use it with the new version v0.2.0

By the way, I saw your [tweets](https://twitter.com/chrisshank23/status/1785422811277979921) [about](https://twitter.com/chrisshank23/status/1785749028506046671) bringing arrows to web components. And I'm looking forward to seeing that we have an easier way to use interactive visual elements on the web.

**Comment by ChrisShank** [comment]
Amazing, thanks so much! Very excited about the arrow stuff too, thanks for making my life a little easier 🙌🏻
